apt_packages:
  - apt-transport-https
  - amazon-ecr-credential-helper
  - ca-certificates
  - curl
  - docker-ce
  - docker-ce-cli
  - jq
  - python3-pip
  - python3-setuptools
  - software-properties-common
pip_packages:
  - ansible==4.0.0
  - awscli==1.19.39
  - boto3==1.17.39
  - docker==4.4.4
  - docker-compose==1.28.6

default_user: &default_user
  name: asp
  uid: 1000
  home: "/home/asp"
  groups: []
  package_groups:
    - docker
  shell: "/bin/bash"
  sudo: yes

users:
  - *default_user

node_exporter:
  version: "1.1.1"
  url: "https://github.com/prometheus/node_exporter/releases/download/v1.1.1/node_exporter-1.1.1.linux-amd64.tar.gz"
  config_flags:
    'web.listen-address': '0.0.0.0:10000'
    'log.level': 'info'

bootstrap:
  ansible_dir: "/home/asp/ansible/"
  ansible_script_path: "/home/asp/ansible/ansible.sh"
