---

  - name: docker-config - create docker config dir
    file:
      path: "/home/asp/.docker"
      state: directory
      owner: asp
      group: asp
    tags: [ docker-config ]

  - name: docker-config - add docker config file
    copy:
      src: files/docker-config.json
      dest: "/home/asp/.docker/config.json"
      owner: asp
      group: asp
      mode: 0744
    tags: [ docker-config ]
